### ISSUE TITLE
Creating a new file in the project

### ISSUE THREAD

**Issue by Taruu** [Vladg24YT/Oclide#5]
Why is it necessary to specify an absolute path for the file?
![image](https://user-images.githubusercontent.com/24312612/104834299-86432300-58af-11eb-81d0-f87038b45f12.png)

**Comment by Vladg24YT** [comment]
> Why is it necessary to specify an absolute path for the file?

This is done in order to add flexibility in managing the location of the created files.

**Comment by Taruu** [comment]
> > Why is it necessary to specify an absolute path for the file?
> 
> This is done in order to add flexibility in managing the location of the created files.

I have not seen such functionality in other IDEs because, logically, all files are in the project folder

**Comment by Vladg24YT** [comment]
Fixed. Now only file name is prompted.
