### ISSUE TITLE
OCEemu launch

### ISSUE THREAD

**Issue by Taruu** [Vladg24YT/Oclide#6]
the system keeps all files in tmp even after installation.
If OCEmu is running all IDE controls are blocked.
it is not clear where to look for the project file to run it
![image](https://user-images.githubusercontent.com/24312612/104834477-97406400-58b0-11eb-8c40-19d7249fa39a.png)

**Comment by Vladg24YT** [comment]
> the system keeps all files in tmp even after installation.

Fixed. Now OpenOS is being installed at `tmpfs` directory.

> If OCEmu is running all IDE controls are blocked.

Fixed. OCEmu is now running in a seperate Thread:

![image](https://user-images.githubusercontent.com/35247077/104851703-b3bbbb00-5907-11eb-87fd-5e12460a5e59.png)

> it is not clear where to look for the project file to run it

All projects are now being copied into the `/home` directory
